/**
 * Invariant: transcript finder picks the file generated by THIS session,
 * not whichever jsonl in the project dir happens to have the newest
 * mtime. Protects against concurrent-session attribution bugs and
 * streams the file instead of loading it whole into memory.
 *
 * Audit finding #8 (2026-04-21).
 */
import { describe, it, expect } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';

const src = fs.readFileSync(
  path.join(__dirname, '..', 'src', 'core', 'spawn.ts'),
  'utf-8',
);

describe('transcript session attribution (source invariants)', () => {
  it('findLatestTranscript (mtime-only)는 더 이상 존재하지 않는다', () => {
    // Active code path (comments stripped)
    const codeOnly = src
      .split('\n')
      .filter((l) => !/^\s*(\/\/|\*|\/\*)/.test(l))
      .join('\n');
    expect(codeOnly).not.toMatch(/function findLatestTranscript\b/);
    expect(codeOnly).toMatch(/function findSessionTranscript\b/);
  });

  it('세션 시작 시점의 스냅샷을 캡처한다', () => {
    expect(src).toMatch(/snapshotExistingTranscripts/);
    expect(src).toMatch(/const preSnapshot = snapshotExistingTranscripts/);
  });

  it('스냅샷 diff + 세션 시작 이후 mtime으로 후보를 걸러낸다', () => {
    expect(src).toMatch(/!preSnapshot\.has\(f\)/);
    expect(src).toMatch(/mtime >= sessionStartMs/);
  });

  it('transcript 내용은 streaming으로 읽는다 (readFileSync 전체 로드 금지)', () => {
    const codeOnly = src
      .split('\n')
      .filter((l) => !/^\s*(\/\/|\*|\/\*)/.test(l))
      .join('\n');
    // 전체 읽기 패턴이 제거됐는지
    expect(codeOnly).not.toMatch(/fs\.readFileSync\(transcript, ['"]utf-8['"]\)/);
    // streaming 헬퍼 존재
    expect(codeOnly).toMatch(/function countUserMessages/);
    expect(codeOnly).toMatch(/createReadStream/);
  });
});

describe('countUserMessages streaming (runtime)', () => {
  it('user/queue-operation 타입만 카운트한다', async () => {
    // Runtime test via the exported function path (spawn.ts exports via internals
    // not guaranteed — 대신 읽기 로직을 재현해 셈법만 검증)
    const tmpFile = `/tmp/forgen-transcript-test-${process.pid}.jsonl`;
    fs.writeFileSync(
      tmpFile,
      [
        '{"type":"user","text":"a"}',
        '{"type":"assistant","text":"b"}',
        '{"type":"queue-operation","text":"c"}',
        '',
        'not-json',
        '{"type":"user","text":"d"}',
      ].join('\n'),
    );
    try {
      const { createInterface } = await import('node:readline');
      const stream = fs.createReadStream(tmpFile, { encoding: 'utf-8' });
      const rl = createInterface({ input: stream, crlfDelay: Infinity });
      let count = 0;
      for await (const line of rl) {
        if (!line) continue;
        try {
          const t = (JSON.parse(line) as { type?: unknown }).type;
          if (t === 'user' || t === 'queue-operation') count++;
        } catch { /* skip */ }
      }
      rl.close();
      stream.close();
      expect(count).toBe(3);
    } finally {
      fs.unlinkSync(tmpFile);
    }
  });
});
