// forgen-managed — do not edit; regenerated by `forgen install opencode`
/**
 * forgen — OpenCode plugin (W3-3 P1). `tool.execute.before` 를 forgen 결정적 가드로 브릿지:
 *   {tool, args} → forgen opencode-guard → block 이면 throw(도구 차단).
 * 얇은 shim — 번역/가드 로직은 forgen 소유(drift-free). async execFile(이벤트루프 비차단).
 * GUARD_CMD 는 install-opencode 가 절대경로로 치환(런타임 PATH 비의존).
 */
import { execFile } from "node:child_process"

// forgen:guard-cmd — install-opencode 가 이 배열을 [node, <절대 cli 경로>, opencode-guard] 로 치환
const GUARD_CMD: string[] = ["forgen", "opencode-guard"]

export const forgen = async () => ({
  "tool.execute.before": async (
    input: { tool?: string },
    output: { args?: Record<string, unknown> },
  ) => {
    const decision = await new Promise<{ block?: boolean; reason?: string }>((resolve) => {
      const [cmd, ...rest] = GUARD_CMD
      const child = execFile(cmd, rest, { timeout: 8000, encoding: "utf-8" }, (err, stdout) => {
        if (stdout) {
          try {
            resolve(JSON.parse(stdout))
            return
          } catch {
            /* fall through to fail-open */
          }
        }
        if (err) console.error("[forgen] opencode-guard 호출 실패(fail-open):", err.message)
        resolve({ block: false })
      })
      child.stdin?.end(JSON.stringify({ tool: input?.tool, args: output?.args }))
    })
    if (decision.block) throw new Error(decision.reason || "[forgen] blocked by guard")
  },
})

export default forgen
